### ISSUE TITLE
Error: Invariant failed: No builder configured in core.builder

### ISSUE THREAD

**Issue by thnaylor** [chakAs3/nuxt-storybook-module-demo#1]
## Expected Behavior
- Fresh clone of repo to start without errors.

## Actual Behavior
- After starting storybook the following error is displayed.

```
Error: Invariant failed: No builder configured in core.builder
    at invariant (.\node_modules\tiny-invariant\dist\tiny-invariant.cjs.js:14:11)
    at buildDevStandalone (.\node_modules\@storybook\core-server\dist\index.js:116:1867)
    at async withTelemetry (.\node_modules\@storybook\core-server\dist\index.js:101:3903)
    at async dev (.\node_modules\@storybook\cli\dist\generate.js:471:401)
    at async Command.<anonymous> (.\node_modules\@storybook\cli\dist\generate.js:473:225)
 ```

## Steps to Reproduce the Problem

  1. Clone repo to local system
  2. Install dependencies
  3. Run storybook
  
## Comments
Tried configuring with vite builder as core but receive more errors.

`Expected your framework's preset to export a `renderToCanvas` field.`

**Comment by alniv94** [comment]
+
